# Book settings
title: "CH40208: Topics in Computational Chemistry"
author: Andrew R. McCluskey & Benjamin J. Morgan
logo: pic.png

latex:
  latex_documents:
    targetname: book.tex

#parse:
#  myst_extended_syntax: true
