# Book settings
title: "CH40208: Topics in Computational Chemistry"
author: Andrew R. McCluskey & Benjamin J. Morgan
logo: pic.png

latex:
  latex_documents:
    targetname: book.tex

parse:
  myst_extended_syntax: true

sphinx:
  config:
    mathjax_config:
      TeX:
        Macros:
          "bvec": ["\\mathbf{#1}", 1]
          "cvec": ["\\begin{bmatrix}#1\\\\#2\\end{bmatrix}", 2]
          "norm": ["\\left\\lVert #1\\right\\rVert", 1]
